# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='url',
        ),
    ]
