# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0003_auto_20170405_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.BigIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='unlikes',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
