# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0004_auto_20170406_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='TEST', max_length=1000),
            preserve_default=False,
        ),
    ]
