# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0005_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='numberviews',
            field=models.BigIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
