# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0010_auto_20170421_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='numberviews',
            field=models.BigIntegerField(default=0),
        ),
    ]
