# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0012_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='live_at',
            field=models.DateField(null=True),
        ),
    ]
